version: "2"
linters:
  default: none
  enable:
    - errcheck
    - funlen
    - goconst
    - gocyclo
    - govet
    - ineffassign
    - rowserrcheck
    - staticcheck
    - unused
  settings:
    errcheck:
      check-type-assertions: true
    funlen:
      lines: 150
      statements: 100
    goconst:
      min-len: 2
      min-occurrences: 2
    gocritic:
      enabled-checks:
        - nestingReduce
      settings:
        nestingReduce:
          bodyWidth: 5
    gocyclo:
      min-complexity: 30
    lll:
      line-length: 120
  exclusions:
    generated: lax
    presets:
      - common-false-positives
      - std-error-handling
    rules:
      - linters:
          - staticcheck
        text: 'SA1019: package github.com/golang/protobuf'
      - linters:
          - staticcheck
        text: 'SA6002: argument should be pointer-like to avoid allocations'
      - linters:
          - structcheck
        text: Store` is unused
      - linters:
          - lll
        source: '^//go:generate '
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$