name: Okteto Devflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  devflow:
    runs-on: ubuntu-latest
    env:
      ENV: dev
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: context
        uses: okteto/context@latest
        with:
          token: ${{ secrets.OKTETO_TOKEN }}

      - name: "Trigger the pipeline"
        uses: okteto/pipeline@latest
        with:
          name: go-gin-gorm-starter
          timeout: 8m
          skipIfExists: false
          namespace: smarter-wallet
          variables: ""